---
kind: pipeline
type: docker
name: debian-unstable

steps:
- name: debian-build
  image: dankamongmen/unstable_builder:2019-12-30a
  commands:
    - apt-get update
    - apt-get -y dist-upgrade
    - apt-get -y install devscripts git-buildpackage locales
    - echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen
    - locale-gen
    - export LANG=en_US.UTF-8
    - mk-build-deps --install -t'apt-get -y'
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make
    - make test
---
kind: pipeline
type: docker
name: ubuntu-focal

steps:
- name: ubuntu-build
  image: dankamongmen/focal:2019-12-30c
  commands:
    - apt-get update
    - apt-get -y dist-upgrade
    - env DEBIAN_FRONTEND=noninteractive apt-get -y install devscripts git-buildpackage equivs locales
    - mk-build-deps --install -t'apt-get -y'
    - echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen
    - locale-gen
    - export LANG=en_US.UTF-8
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make
    - make test || ./notcurses-tester -p ../data
