---
kind: pipeline
type: docker
name: debian-unstable

steps:
- name: debian-build
  image: dankamongmen/unstable_builder:2020-06-19a
  commands:
    - export LANG=en_US.UTF-8
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release # -DUSE_RUST=yes -DUSE_NETWORK=yes
    - make
    - make test
---
kind: pipeline
type: docker
name: ubuntu-focal

steps:
- name: ubuntu-build
  image: dankamongmen/focal:2020-06-19a
  commands:
    - export LANG=en_US.UTF-8
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_MULTIMEDIA=none ..
    - make
    - make test
---
kind: pipeline
type: docker
name: fedora-rawhide

steps:
- name: fedora-rawhide
  image: dankamongmen/fedora33:2020-06-19a
  commands:
    - export LANG=en_US.UTF-8
    - dnf install -y doctest-devel
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_MULTIMEDIA=oiio ..
    - make
    - make test
