---
kind: pipeline
type: docker
name: debian-unstable

steps:
- name: debian-build
  image: debian:unstable-slim
  commands:
    - export LANG=en_US.UTF-8
    - export TERM=xterm
    - apt-get update -y
    - apt-get install -y ncurses-dev pkgconf libqrcodegen-dev libavdevice-dev cmake build-essential doctest-dev libunistring-dev libdeflate-dev libgpm-dev pandoc locales
    - echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
    - locale-gen
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_STATIC=off -DUSE_GPM=on -DUSE_QRCODEGEN=on -DDFSG_BUILD=on -DBUILD_FFI_LIBRARY=on
    - make -j2
    - ./notcurses-info
    - ctest --output-on-failure
    - make install
    - ldconfig
    - apt-get install -y python3-setuptools python3-wheel python3-pip python3-pypandoc python3-cffi-backend
    - cd ../cffi
    - LDFLAGS=-L/usr/local/lib CFLAGS=-I/usr/local/include python3 setup.py sdist build install
    - env LD_LIBRARY_PATH=/usr/local/lib ./notcurses-pydemo > /dev/null
    - env LD_LIBRARY_PATH=/usr/local/lib ./ncdirect-pydemo > /dev/null
---
kind: pipeline
type: docker
name: fedora-rawhide

steps:
- name: fedora-rawhide
  image: dankamongmen/rawhide:2021-11-14a
  commands:
    - export LANG=en_US.UTF-8
    - export TERM=xterm
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_DEFLATE=off -DUSE_MULTIMEDIA=oiio -DUSE_QRCODEGEN=on ..
    - make -j2
    - ./notcurses-info
    - ctest --output-on-failure
    - make install
    - ldconfig
    - cd ../cffi
    - LDFLAGS=-L/usr/local/lib CFLAGS=-I/usr/local/include python3 setup.py sdist build install
    - cd ../python
    - LDFLAGS=-L/usr/local/lib CFLAGS=-I/usr/local/include python3 setup.py sdist build install
    - env LD_LIBRARY_PATH=/usr/local/lib ./notcurses-pydemo > /dev/null
    - env LD_LIBRARY_PATH=/usr/local/lib ./ncdirect-pydemo > /dev/null
---
kind: pipeline
type: docker
name: ubuntu-jellyfish

steps:
- name: ubuntu-build
  image: dankamongmen/impish:2021-11-14b
  commands:
    - export LANG=es_ES.UTF-8
    - export TERM=xterm
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_DOCTEST=off -DUSE_QRCODEGEN=on -DUSE_MULTIMEDIA=none ..
    - make -j2
    - ./notcurses-info
    - ctest --output-on-failure
    - make install
    - ldconfig
    - cd ../cffi
    - python3 setup.py sdist build
    - cd ../python
    - LDFLAGS=-L/usr/local/lib CFLAGS=-I/usr/local/include python3 setup.py sdist build install
---
kind: pipeline
type: docker
name: alpine-edge

steps:
- name: alpine-edge
  image: dankamongmen/edge_builder:2022-01-07a
  commands:
    - export LANG=en_US.UTF-8
    - export TERM=vt100
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_PANDOC=off ..
    - make -j2
    - ./notcurses-info
    - ctest --output-on-failure
---
kind: pipeline
type: docker
name: gentoo

steps:
- name: gentoo
  image: dankamongmen/gentoo:2022-02-07a
  commands:
    - export LANG=C.UTF-8
    - export TERM=xterm
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_PANDOC=off -DUSE_DOCTEST=off -DUSE_DEFLATE=off ..
    - make -j2
    - ./notcurses-info
    - ctest --output-on-failure
