---
kind: pipeline
type: docker
name: debian-unstable

steps:
- name: debian-build
  image: dankamongmen/unstable_builder:2020-10-10a
  commands:
    - export LANG=en_US.UTF-8
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make
    - env TERM=xterm make test
    - make install
    - cd ../python
    - LDFLAGS=-L/usr/local/lib CFLAGS=-I/usr/local/include python3 setup.py sdist build install
    - env TERM=xterm LD_LIBRARY_PATH=/usr/local/lib ./notcurses-pydemo
    - env TERM=xterm LD_LIBRARY_PATH=/usr/local/lib ./notcurses-direct-pydemo > /dev/null
---
kind: pipeline
type: docker
name: ubuntu-focal

steps:
- name: ubuntu-build
  image: dankamongmen/focal:2020-10-10a
  commands:
    - export LANG=en_US.UTF-8
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_MULTIMEDIA=none ..
    - make
    - env TERM=xterm make test
    - make install
    - cd ../python
    - python3 setup.py sdist build
    - cd ../rust
    - cargo build
    - cargo t
---
kind: pipeline
type: docker
name: fedora-rawhide

steps:
- name: fedora-rawhide
  image: dankamongmen/fedora33:2020-09-29a
  commands:
    - export LANG=en_US.UTF-8
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_MULTIMEDIA=oiio ..
    - make
    - env TERM=xterm make test
