---
kind: pipeline
type: docker
name: debian-unstable

steps:
- name: debian-build
  image: dankamongmen/unstable_builder:2021-02-01a
  commands:
    - export LANG=en_US.UTF-8
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j2
    - env TERM=xterm ctest
    - make install
    - ldconfig
    - cd ../cffi
    - LDFLAGS=-L/usr/local/lib CFLAGS=-I/usr/local/include python3 setup.py sdist build install
    - env TERM=xterm LD_LIBRARY_PATH=/usr/local/lib ./notcurses-pydemo > /dev/null
    - env TERM=xterm LD_LIBRARY_PATH=/usr/local/lib ./notcurses-direct-pydemo > /dev/null
    - cd ../rust
    - rustc --version
    - cargo build
    - env TERM=xterm cargo t_all
---
kind: pipeline
type: docker
name: alpine-edge

steps:
- name: alpine-edge
  image: dankamongmen/edge_builder:2021-01-08a
  commands:
    - export LANG=en_US.UTF-8
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_QRCODEGEN=off -DUSE_PANDOC=off ..
    - make -j2
    - env TERM=xterm ctest
---
kind: pipeline
type: docker
name: fedora-rawhide

steps:
- name: fedora-rawhide
  image: dankamongmen/fedora34:2021-01-08b
  commands:
    - export LANG=en_US.UTF-8
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_MULTIMEDIA=oiio ..
    - make -j2
    - env TERM=xterm ctest
    - make install
    - ldconfig
    - cd ../rust
    - rustc --version
    - cargo build
    - env TERM=xterm cargo t_all
---
kind: pipeline
type: docker
name: ubuntu-focal

steps:
- name: ubuntu-build
  image: dankamongmen/hirsute:2021-02-01a
  commands:
    - export LANG=es_ES.UTF-8
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_MULTIMEDIA=none ..
    - make -j2
    - env TERM=xterm ctest -V
    - make install
    - ldconfig
    - cd ../cffi
    - python3 setup.py sdist build
