---
kind: pipeline
type: docker
name: debian-unstable

steps:
- name: debian-build
  image: dankamongmen/unstable_builder:2020-08-14a
  commands:
    - export LANG=en_US.UTF-8
    - apt-get install -y libunistring-dev
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make
    - env TERM=xterm make test
---
kind: pipeline
type: docker
name: ubuntu-focal

steps:
- name: ubuntu-build
  image: dankamongmen/focal:2020-08-14a
  commands:
    - export LANG=en_US.UTF-8
    - apt-get install -y libunistring-dev
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_MULTIMEDIA=none ..
    - make
    - env TERM=xterm make test
---
kind: pipeline
type: docker
name: fedora-rawhide

steps:
- name: fedora-rawhide
  image: dankamongmen/fedora33:2020-07-13a
  commands:
    - export LANG=en_US.UTF-8
    - dnf install -y libunistring-devel
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_MULTIMEDIA=oiio ..
    - make
    - env TERM=xterm make test
