---
kind: pipeline
type: docker
name: debian-unstable

steps:
- name: debian-build
  image: dankamongmen/unstable_builder:2020-04-18e
  commands:
    - export LANG=en_US.UTF-8
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release # -DUSE_RUST=yes -DUSE_NETWORK=yes
    - make
    - make test || ./notcurses-tester -p ../data
---
kind: pipeline
type: docker
name: ubuntu-focal

steps:
- name: ubuntu-build
  image: dankamongmen/focal:2020-04-18c
  commands:
    - export LANG=en_US.UTF-8
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make
    - make test || ./notcurses-tester -p ../data
