---
kind: pipeline
type: docker
name: debian-unstable

steps:
- name: debian-build
  image: dankamongmen/unstable_builder:2020-05-23a
  commands:
    - export LANG=en_US.UTF-8
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release # -DUSE_RUST=yes -DUSE_NETWORK=yes
    - make
    - ./notcurses-tester -p ../data
---
kind: pipeline
type: docker
name: ubuntu-focal

steps:
- name: ubuntu-build
  image: dankamongmen/focal:2020-05-23a
  commands:
    - export LANG=en_US.UTF-8
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make
    - ./notcurses-tester -p ../data
---
kind: pipeline
type: docker
name: fedora-rawhide

steps:
- name: fedora-rawhide
  image: dankamongmen/fedora_builder:2020-05-28a
  commands:
    - export LANG=en_US.UTF-8
    - dnf -y update --refresh
    - dnf -y upgrade
    - dnf -y install make cmake libqrcodegen-devel gcc-c++ OpenImageIO-devel pandoc python3-cffi python3-devel pkgconfig ncurses-devel
    - mkdir build
    - cd build
    - ls
    - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_MULTIMEDIA=oiio ..
    - make
    - ./notcurses-tester -p ../data
