#!/bin/sh
set -e

# --------------------- copied from dh-python 4.20191017 ---------
if which py3clean >/dev/null 2>&1; then
  py3clean -p python3-notcurses.interface 
else
  dpkg -L python3-notcurses.interface | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
  find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi
# --------------------- end material copied from dh-python -------
