.TH notcurses-planereel 1 "2019-12-25"
.SH NAME
notcurses-planereel \- Experiment with panelreels
.SH SYNOPSIS
.B notcurses-planereel
[ \fB\-\-ob \fIbottomoffset \fR]
[ \fB\-\-ot \fItopoffset \fR]
[ \fB\-\-ol \fIleftoffset \fR]
[ \fB\-\-or \fIrightoffset \fR]
[ \fB\-t \fItabletmask \fR]
[ \fB\-b \fIbordermask \fR]
.SH OPTIONS
.TP
.BR \-\-ob \fIbottomoffset\fR
Offset the panelreel some number of rows from the bottom.
.TP
.BR \-\-ot \fItopoffset\fR
Offset the panelreel some number of rows from the top.
.TP
.BR \-\-ol \fIleftoffset\fR
Offset the panelreel some number of columns from the left.
.TP
.BR \-\-or \fIrightoffset\fR
Offset the panelreel some number of columns from the right.
.SH DESCRIPTION
.B notcurses-planereel
A testing and exploration tool for notcurses panelreels. With the program open, press 'a' to create a new panel, or 'd' to delete the focused panel. 'q' quits at any time.
.SH NOTES
Proper display requires a terminal advertising the RGB terminfo(5) capability (necessary for specification of arbitrary 24bpp colors), and a monospaced font with good Unicode support.
.SH SEE ALSO
notcurses(3notcurses), terminfo(5)
